

GET http://localhost:3001/api/auth/signup 
####
GET http://localhost:3001/api/pub/3
######
POST http://localhost:3001/api/auth/signup 
content-type: application/json

{
    "nom": "Février",
    "prenom":"Onze",
    "email": "onz@groupomania.fr",
    "service": "Roquefort",
    "description":"",
    "password": "ooo"  
}
######
POST http://localhost:3001/api/auth/login 
content-type: application/json

{
    "password": "sts",
    "email": "seli@groupomania.fr"
}

######
POST http://localhost:3001/api/auth/login 
######
GET http://localhost:3001/api/auth/modif/31
######
PUT http://localhost:3001/api/auth/modif/18
content-type: application/json

{
    "nom": "Avril",
    "prenom": "Onze",
    "password": "ooo",
    "service": "service modif", 
    "description":"modif aussi"
}
######
DELETE http://localhost:3001/api/auth/delete/72
######
POST http://localhost:3001/api/pub/create/22
content-type: application/json

{
    "titre": "Essai avec user 22",
    "texte_pub": "Voir si ça marche avec user 22"
}
######
POST http://localhost:3001/api/pub/
######
GET http://localhost:3001/api/pub/user/7
######
GET http://localhost:3001/api/pub/
######
POST http://localhost:3001/api/pub/2/like/7
######
GET http://localhost:3001/api/pub/4/like/
######
POST http://localhost:3001/api/pub/4/comm/11
content-type: application/json

{
    "texte": "Moi, je suis là uniquement pour faire un 2e commentaire !"
}
######
GET http://localhost:3001/api/pub/4/comm/
######
GET http://localhost:3001/api/auth/ident/14
