

GET http://localhost:3001/api/auth/signup 
####
GET http://localhost:3001/api/pub/3
######
POST http://localhost:3001/api/auth/signup 
content-type: application/json

{
    "nom": "fff",
    "prenom":"dfd",
    "email": "fd@.fd",
    "service": "cc",
    "description":"",
    "password": ""  
}
######
POST http://localhost:3001/api/auth/login 
content-type: application/json

{
    "password": "sts",
    "email": "seli@groupomania.fr"
}

######
POST http://localhost:3001/api/auth/login 
######
GET http://localhost:3001/api/auth/modif/31
######
PUT http://localhost:3001/api/auth/modif
content-type: application/json

{
    "nom": "Modifé",
    "prenom": "modif Prénom",
    "password": "modif",
    "service": "service modif", 
    "description":"modif aussi"
}
######
DELETE http://localhost:3001/api/auth/delete/72
######
POST http://localhost:3001/api/pub/14
content-type: application/json

{
    "titre": "1er essai",
    "contenu": "Est que cela fonctionne ?"
}
######
POST http://localhost:3001/api/pub/
######
GET http://localhost:3001/api/pub/user/7