

GET http://localhost:3001/api/auth/signup 

######
POST http://localhost:3001/api/auth/signup 
content-type: application/json

{
    "nom": "Blois",
    "prenom":"François",
    "email": "fran@groupo.fr",
    "service": "Logistique",
    "description":"",
    "password": "fff"  
}
### login  ###
POST http://localhost:3001/api/auth/login 
content-type: application/json

{
    "password": "jjj",
    "email": "jose@groupo.fr"
}


### ident user  ###
GET http://localhost:3001/api/auth/ident/22 


######
POST http://localhost:3001/api/auth/login 
######
GET http://localhost:3001/api/auth/modif/31
### modif user ###
PUT http://localhost:3001/api/auth/modif/48
content-type: application/json

{
    "nom": "Balançoire",
    "password":"jjj"
    
}
######

DELETE http://localhost:3001/api/auth/delete/25
### create a publication ###
POST http://localhost:3001/api/pub/create/41
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjpbeyJpZCI6NDEsIm5vbSI6IkhhbmdhciIsInByZW5vbSI6Ikpvc8OpIiwiZW1haWwiOiJqb3NlQGdyb3Vwby5mciIsInNlcnZpY2UiOiJMb2dpc3RpcXVlIiwiZGVzY3JpcHRpb24iOiIiLCJwYXNzd29yZCI6IiQyYiQxMCRRM3RqblZoMFBVT29QLkp3Qk14YnZ1MHpHNVZqY3VpL0U0SmhqMDdDekxCbXNuRVhzOHVLZSIsImxhc3RfY29ubmVjdCI6IjIwMjEtMDEtMTgiLCJwaG90byI6bnVsbH1dLCJpYXQiOjE2MTA5OTI0OTksImV4cCI6MTYxMDk5NjA5OX0.MGzySyLr3u_hD9gfCtwa6NvPHQyoMxGwl7zM5-HhNLU

{
    "titre": "Test via REST client",
    "texte_pub": "bla blab la"
}
######
POST http://localhost:3001/api/pub/
###select a pub###
GET http://localhost:3001/api/pub/16
### select ses publications ###
GET http://localhost:3001/api/pub/user/41
######
GET http://localhost:3001/api/pub/
######
POST http://localhost:3001/api/pub/2/like/7
######
GET http://localhost:3001/api/pub/4/like/
######
POST http://localhost:3001/api/pub/4/comm/11
content-type: application/json

{
    "texte": "Moi, je suis là uniquement pour faire un 2e commentaire !"
}
######
GET http://localhost:3001/api/pub/4/comm/
### get a user by id ###
GET http://localhost:3001/api/auth/ident/30

### delete a pub ###
DELETE http://localhost:3001/api/pub/22
